### ISSUE TITLE
Invalid Extension ID

### ISSUE THREAD

**Issue by tusbar** [ivantsov/redux-webext#2]
Hello,

I’m getting an « Invalid Extension ID » on Firefox on this line : https://github.com/ivantsov/redux-webext/blob/master/src/ui-store.js#L50, when opening the popup.

I initialize the popup with 

```js
async function init() {
    const store = await createUIStore();

    ReactDOM.render(
        <Provider store={ store }>
            <Popup/>
        </Provider>,
        document.getElementById('app')
    );
}

init();
```

And it fails when creating the UI store, so the popup never renders.

Would you happen to know what’s going on? Are there any known issues on Firefox?

Thanks.

**Comment by tusbar** [comment]
@ivantsov OK, I got it.

The `sendMessage` flow declaration is invalid:

```js
sendMessage: (
    msg: any,
    sender?: ?string,
    cb?: (res: Object) => void
) => void,
```

Acording to [MDN](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/sendMessage) and [Chrome Docs](https://developer.chrome.com/extensions/runtime#method-sendMessage).

**Comment by ivantsov** [comment]
Hi @tusbar, thanks for your interest in the project :)
Unfortunately, I haven't tested the package on Firefox yet and currently, I'm on vacation. So, I'm gonna take a look at the issue in a week.

Regarding `sendMessage` the docs says: _"The ID of the extension/app to send the message to. **If omitted, the message will be sent to your own extension/app.** Required if sending messages from a web page for web messaging."_ This's why I think the usage of this API is correct and problem should be somewhere else.

**Comment by tusbar** [comment]
@ivantsov yeah, but it should be the first argument, not the second one.

**Comment by ivantsov** [comment]
Indeed, you're right. Thanks a lot for the PR!

**Comment by tusbar** [comment]
Great! Thank you for merging it in. Cheers. 🍻
