### ISSUE TITLE
when use it with immutable.

### ISSUE THREAD

**Issue by ziyan22** [ivantsov/redux-webext#4]
Hello,

I’m trying to use immutable with redux in my extension. However I found, I could not use any I Immutbale library in popup page. 

I set the initial state in background - index.js page with `store.dispatch(setState(someJsObject))`. setState() is a function I wrote in background - action.js page which is  

```javascript
import { Map } from 'immutable';
function setState(state, newState) {
	return state.merge(newState);
}

export default function(state = Map(), action) {
	switch (action.type) {
		case SET_STATE:
			return setState(state, action.state);
	}
	return state;
}
```

I am able to use immutable method in background page. for example, I can use `store.getState().toJS()` to print nice js format of current state. However I am not able to use such thing in popup page. In Popup page, if I print `store.getState()` a immutable.js structure object will be printed out and contain the information I seted in background page, but if I print `store.getState().toJS()` it will say 'store.getState().toJS() is not a function'?

**Comment by ivantsov** [comment]
Hi @ziyan22,
Can you share an example with the issue?

**Comment by ziyan22** [comment]
I attach the file I create with the issue below~ I printed `store.getState().toJS()` in both backgound -- index.js and popup -- index.js. However in popup -- index.js it said, `store.getState().toJS()` is not a function?


[example.zip](https://github.com/ivantsov/redux-webext/files/739966/example.zip)

**Comment by ivantcov** [comment]
Thanks for the example @ziyan22.

So, the problem is that `redux-webext` uses `chrome.runtime.sendMessage` internally. And according to the docs (https://developer.chrome.com/extensions/runtime#method-sendMessage): *This message should be a JSON-ifiable object.*
In other words, when you provide the app state from _background_ page to _ui_, the state will be converted to JS object, this's why you can't call `.toJS()`.

**Comment by ziyan22** [comment]
Thanks for the reply! Totally understand. I gonna to change immutable to JS object. 

Do you have any example for content_script? I am also trying to use it in content_script, however it seems not working at line [#30](https://github.com/ivantsov/redux-webext/blob/master/src/background-store.js#L30). When it run the callback function from the message, the function at line [#51](https://github.com/ivantsov/redux-webext/blob/master/src/ui-store.js#L51) is not really running?  But it will run correctly when I use it in popup page?

Actually, I am using ff to load my application, I am not sure if it is caused by the difference between ff and chrome.

Here is the example 
[example 2.zip](https://github.com/ivantsov/redux-webext/files/742207/example.2.zip)

**Comment by ivantcov** [comment]
No, there's no an example with content script unfortunately. 

I've tried to run example and it perfectly works on FF and Chrome, without any errors. Might be you use an old version of the browser.

**Comment by ziyan22** [comment]
I am sorry that I did not explain the problem clearly.

so, in the code I am trying to add a [button](https://github.com/ziyan22/exmaple2/blob/master/src/pages/content-script/ContentScript.js#L13) at the end of content of each webpage using `content-script`. However it is not running. If you open the `browser console` of ff, you will get a js error said `promist.then is not a function`

**Comment by ivantsov** [comment]
As I said, I can't reproduce the issue. Try the latest version of the browser or just another browser.

**Comment by ziyan22** [comment]
I guess it is the difference of browser. I ran it in Chrome it is working, but if I run it in the Firefox even the beta version it still gave error in the `browser console`, the button I was trying to add is not showing up. 

This is the error I am getting:
<img width="1269" alt="screen shot 2017-02-01 at 9 41 27 am" src="https://cloud.githubusercontent.com/assets/11093677/22511164/beaf46ae-e862-11e6-9551-f8b9f59c4d2f.png">

**Comment by ziyan22** [comment]
Hey~ 

The problem solved~ I should not include the babel-polyfill in the content-script.  It seems that the Promise polyfill included by babel-polyfill is breaking the chrome.runtime.sendMessage calls used to sync the redux store between the background and the content script.
