### ISSUE TITLE
[Question] About webextension

### ISSUE THREAD

**Issue by AllenFang** [ivantsov/redux-webext#9]
I read some code base in `redux-webext` but I found we use the `chrome` namespace instead of `browser`. For example: https://github.com/ivantsov/redux-webext/blob/master/src/ui-store.js#L31

However, I'm not sure if I got some misunderstanding, if we base on [WebExtensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions) standard, we are suppose to use `browser` instead of `chrome`, right?

any idea about this?

**Comment by ivantsov** [comment]
The [docs](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities) says that:

> As a porting aid, the Firefox implementation of WebExtensions supports chrome, using callbacks, as well as browser, using promises. This means that many Chrome extensions will just work in Firefox without any changes. However, this is not part of the WebExtensions standard, and might not be supported by all compliant browsers.

So, right now using `chrome` works for Chrome and Firefox.

**Comment by AllenFang** [comment]
Yes, that's right, but I think use `browser` will be much standard, WebExtensions standard  can be used on chrome, opera, FF and Edge.  But if we use `chrome` namespace that will be unable on Edge.

**Comment by ivantsov** [comment]
> WebExtensions standard can be used on chrome

Can you please share a link where you've got this info? afaik Chrome doesn't support WebExtension but their own architecture, which is quite similar to WebExtensions.

**Comment by AllenFang** [comment]
hmm.. sorry my mistake, chrome doesn't support the WebExtension absolutely. However, we can use polyfill to make WebExtension works on chrome.

**Comment by ivantsov** [comment]
Unfortunately, I don't think it's a good idea to force people using polyfill when it's absolutely unnecessary. If it happens someday that Firefox stops supporting `chrome` namespace then I'd revisit the issue.

**Comment by AllenFang** [comment]
Thanks @ivantsov

**Comment by bboydflo** [comment]
I am having some issues on firefox 61.0.2 using redux-webext. `chrome is not defined`
I think the error has something to do with a [firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1443253) regarding out of process frames.

On the bug report page is says: 

> Chrome supports out-of-process frames, so Chrome is able to render an extension frame in an extension process (and the iframe can safely be granted access to extension APIs - https://bugs.chromium.org/p/chromium/issues/detail?id=550151 ).
In contrast, Firefox does not support out-of-process frames, so the iframe is handled by a non-extension process (with only limited access to extension APIs).
